# Workflow B: Publish to CocoaPods

name: Publish to CocoaPods

on:
  repository_dispatch:
    types: [trigger-publishCocoapods-workflow]  # Listen for trigger event from Workflow A

jobs:
  publish:
    runs-on: publishCocoapods  # Update this to the appropriate environment

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create directory for downloaded artifacts
        run: mkdir -p ./downloaded  # 确保目录存在

      - name: List files in current directory
        run: ls -al

      - name: Download zip from remote server
        run: |
          curl -O "${{ github.event.client_payload.url }}"
          unzip ${{ github.event.client_payload.archive_name }} -d ./extracted

      - name: Replace xcframework in private repo & update podspec
        run: |
          set -e
          REPO_DIR="/Users/imqatest/Desktop/iOS/PublishSDKONCocoapods"  # Update the path to your repo directory
          DEST_DIR="$REPO_DIR/IMQACore/Frameworks"
          PODSPEC_FILE="$REPO_DIR/IMQACore.podspec"
          VERSION=${{ github.event.client_payload.version }}  # Extract version from the payload

          echo "Updating to version $VERSION"
          rm -rf "$DEST_DIR"/*  # Clear out the old xcframework
          cp -R ./extracted/* "$DEST_DIR"  # Copy new xcframework into repo

          # Update the version in podspec file
          sed -i '' "s/s.version *= *\"[0-9.]*\"/s.version = \"$VERSION\"/" "$PODSPEC_FILE"

          # Commit changes and push to Git
          cd "$REPO_DIR"
          git add .
          git commit -m "chore: 更新版本至 $VERSION"
          git tag "$VERSION"
          git push origin main
          git push origin "$VERSION"

      - name: Push to CocoaPods
        run: |
          cd "$REPO_DIR"
          cat IMQACore.podspec
          # pod trunk push IMQACore.podspec --allow-warnings  # Push the updated podspec to CocoaPods
